### ISSUE TITLE
Consistent Object and String

### ISSUE THREAD

**Issue by Kenright12345** [SamedhG/Queue-API#2]
Would you be opposed to using the piazza post @166 implementation of String and Object?

**Comment by tomharmon** [comment]
Yes, see https://piazza.com/class/k51bluky59n2jr?cid=248

If you were concerned about the extra methods in the string class, I just removed those a few hours ago. If that wasn't it, was there something else specific you needed?

**Comment by Kenright12345** [comment]
That works, thanks! We'll let you know if we need anything else.

**Comment by Kenright12345** [comment]
The Object and String classes are now missing some methods that we may need that are found in the implementations they provided us

https://piazza.com/class/k51bluky59n2jr?cid=166

Can you add these in, if not that's fine.

**Comment by tomharmon** [comment]
Wait so another group whose API you received is using the implementations from https://piazza.com/class/k51bluky59n2jr?cid=166 ?

If so I think you should point them at https://piazza.com/class/k51bluky59n2jr?cid=248
and the hashing/mutation issue and recommend they use my `Object.h` and `String.h`. Personally my opinion is that it might be better if they can use our object and string to avoid that issue, though not claiming mine is exclusively better :D just think it solves some issues.

If there was something else specific from @166 that you are required to have, like `print()`, i would be happy to add that.

Edit: oops didn't mean to open and close it so many times, that was an accident

**Comment by Kenright12345** [comment]
I'll ask, in the mean time can you add a constructor and destructor for queue?

**Comment by Kenright12345** [comment]
And constructor and destructor methods for the object class?

**Comment by tomharmon** [comment]
Done!

**Comment by tomharmon** [comment]
Any luck consolidating?

**Comment by brycedewitt** [comment]
Hey guys, my team also received your repo to implement.

Just for context, the Array we have to implement is an `Array` superclass, with subclasses for `IntArray`, `BoolArray`, `FloatArray`, and `ObjectArray` (for which String is a subclass of `Object`).  Would @Kenright12345  and your partner object to @thomasharmon808 doing the same thing for Queue? The `ObjectQueue` would still support all the same methods and implementations and whatnot (in that you could have `IntWrapper` that also extends object, and likewise for float and bool),  but the other primitive-type Queues would support all the same operations for a single primitive data type without having to wrap and unwrap from objects first.  

We're definitely open to discussion on this, but that's the implementation for Queue that would best work with the other data structures we have.

**Comment by SamedhG** [comment]
Hey, I'm the second designer of this API, While we are willing to make this change, In my personal opinion the wrapper classes would make much more sense. It would reduce code duplication highly. While we would be forced to cast a lot in places that use the API, it would be much cleaner than having to duplicate every change in 4 places. Since the fields of these classes will need to be of different types Implementers will be forced to replicate every change to any method in all implementations. This is extremely bug prone. If you guys and @Kenright12345 and his partner still want 4 separate API's we will make the change.

**Comment by brycedewitt** [comment]
Here's the piazza post we're looking at: https://piazza.com/class/k51bluky59n2jr?cid=331

Mainly, we're looking at the response from Jan:
`ia.push_back( 42 );`
`int r = ia.get( 0 );`
vs.
`ia.push_back( (void*) 42 );`
`int r = (int) ia.get( 0 );`

Essentially, we just agree that `myintarry.push_back( 42 );` is a more reasonable way to add to the array.  @Kenright12345, do you guys have anything to add?

**Comment by SamedhG** [comment]
I agree. This is just a matter of prioritizing code maintainability or user experience. while the prior is a better user experience, It is a much worse for code maintainability. Note: Java developers followed pattern 2 until generics were added to the language.

**Comment by SamedhG** [comment]
It is not to much work from our stand point to copy the API 3/4 times, we just think it is worse long term

**Comment by tomharmon** [comment]
since vitek is going to make this a big deal I added a specific stringqueue class https://github.com/SamedhG/Queue-API/issues/5

You dont need intqueue, floatqueue, etc though, check the assignment description. only object queue and string queue

@brycedewitt

**Comment by tomharmon** [comment]
@Kenright12345 I'm going to close this since I just added the object and string from this post:

https://piazza.com/class/k51bluky59n2jr?cid=345

Please open another issue if that won't work for you

**Comment by brycedewitt** [comment]
all good, thanks guys
