### ISSUE TITLE
shallow or deep equals?

### ISSUE THREAD

**Issue by sudopluto** [SamedhG/Queue-API#4]
could you add to the api if equals() should be based on the queue instance or the contents of the queue?

**Comment by tomharmon** [comment]
It will be deep equals, but I am not around to commit the changes right now. I should be in less than 3 hours though, and will commit the changes then.

**Comment by sudopluto** [comment]
okay, sounds good. now that we looked at the tests, the tests also specify deep equals

**Comment by tomharmon** [comment]
just pushed a commit clarifying the documentation
